export LANG=ja_JP.UTF-8
export LEuSCHARSET=utf-8
export GOPATH="$HOME/.go/"
export EDITOR=/Applications/MacVim.app/Contents/MacOS/Vim
export PATH=~/.composer/vendor/bin:~/dotfiles/bin:/usr/local/opt/coreutils/libexec/gnubin:/Applications/MacVim.app/Contents/MacOS:~/Applications/Vagrant/bin/:/usr/local/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:~/bin:$GOPATH/bin/:$PATH
#export PATH=/usr/local/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:~/bin:$PATH
#export PATH=~/Applications/Vagrant/bin/:$PATH
#export PATH=/Applications/MacVim.app/Contents/MacOS:$PATH
#export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
#export PATH=$GOPATH/bin:$PATH
# export PATH=~/dotfiles/bin:$PATH
